### ISSUE TITLE
Filter by Group & Export Issues

### ISSUE THREAD

**Issue by RyanPavlich** [tim-salabim/leaflet.glify#5]
Problem:
The filter by group button does not seem to work when I use addGliffyPoints. The filter box will appear on the screen, however nothing happens when it is clicked. 

Questions: 
1. How can I enable the filter by group function to work with GlifyPoints?

2. Does leaflet.Glify only run on local machines? I have been unable to export as a webpage and via markdown? I will try shiny next.

Code:
```r
leaflet() %>%
  addProviderTiles(provider = providers$CartoDB.Positron) %>%
  setView(lng = -95.7129, lat = 37.0902, zoom = 6)%>%
  addGlifyPoints(data = df_pts1, color = cbind(0, 0.2, 1), Opacity = 0.8, weight = 3, group = "A") %>%
  addGlifyPoints(data = df_pts2, color = cbind(1, 0.2, .5), Opacity = 0.8, weight = 3, group = "B") %>%
  addMouseCoordinates() %>%
addLayersControl(
  overlayGroups = c("A", "B"),
  options = layersControlOptions(collapsed = FALSE))
```
Thank you for any help!

**Comment by tim-salabim** [comment]
Sorry for the late reply. This is currently not possible. I am not sure whether it will ever be... I will certainly look into it

**Comment by tim-salabim** [comment]
With this commit it is now possible to use `addLayersControl` with both `addGlifyPoints` and `addGlifyPolygons`. 

As for your second question, it is possible to include them in markdown but you need to set `self_contained: true` in your yaml header. 
As for shiny, currently not possible. Will try to support it though

**Comment by RyanPavlich** [comment]
Hi Tim! No worries at all - thank you for replying. I was unable to export the map via Markdown. I got the following PanDoc error: 

Could not determine mime type for ... Leaflet.glify

Ultimately I was able to complete my task to using Mapbox. 

Thanks for the package Tim!  Have a great evening. 

- Ryan P

**Comment by tim-salabim** [comment]
Sorry, my bad. I updated my comment. `self_contained` should be `false`.

**Comment by tim-salabim** [comment]
I just added a note on how to get it to work with shiny to the readme, so am closing this issue here as all questions should be answered
