### ISSUE TITLE
Inability to Reproduce Example Code

### ISSUE THREAD

**Issue by Jesse-Kerr** [tim-salabim/leaflet.glify#7]
Hi,

I really appreciate this package. However, I tried to reproduce your first example (the one without colors), and was unable to see the blue dots, only the black tiles on the leaflet map. My code was verbatim copy and paste from the first example. 

Any idea why this is?

Thanks,

Jesse

**Comment by HellaRam** [comment]
As an update, I have updated all of my packages to see if that fixes the problem.

**Comment by tim-salabim** [comment]
I assume it didn't?
Can you please open the browser console (ctrl + shift + i and then select tab console) and screenshot what it shows.

It still works for me without any problem. I am on ubuntu using firefox

**Comment by HellaRam** [comment]
![github_error_glify_gl_files](https://user-images.githubusercontent.com/15010606/48971669-d9303100-efea-11e8-861a-33f5ebb16298.JPG)

I am using Google Chrome on Windows 10

**Comment by HellaRam** [comment]
I have limited experience with Javascript, so I'm not sure what the errors in the Developer Console mean. I am in the process of learning it, however, so if there is any way I can help with the development I can certainly try. I will start by seeing whether it works in Firefox on my machine.

**Comment by tim-salabim** [comment]
A quick google search points towards limited resources being made available by the os or limited gpu resources. Do you have any other webgl instances already running when these errors happen? Have you tried with less, say 1000, points?

**Comment by HellaRam** [comment]
I just tried with 1000 points and it did work.

**Comment by HellaRam** [comment]
I don't think I have any other webgl instances running.

**Comment by tim-salabim** [comment]
I just tried on my work machine which also has windows 10 and it works just fine with 1m points. I guess it's an issue of your hardware setup, likely your graphics card (I have Intel HD graphics 620) or your RAM (I have 16Gb). 
With the standard example of 1m points, my windows machine uses about 6.5Gb RAM in standard useage mode (i.e. having a few firefox tabs, outlook and skype open). 
You could try to figure out your limitations by trying different amounts of points.

**Comment by Jesse-Kerr** [comment]
Hi @tim-salabim I haven't followed up on it since I have transitioned to the Javascript glify plugin. We can close it, it seems to be something on my side. Thanks for your help.

**Comment by tim-salabim** [comment]
Thanks for checking back in.
