### ISSUE TITLE
Add info about the leaflet.glify:::glifyDependencies() order, or create a glifyOutput() function

### ISSUE THREAD

**Issue by ColinFay** [tim-salabim/leaflet.glify#8]
Hey, 

Thanks for this awesome package. 

If I compare these two pieces of code (after the initial bloc) : 

``` r
library(mapview)
library(leaflet)
library(leaflet.glify)
library(sf)
library(colourvalues)


m = leaflet() %>%
  addProviderTiles(provider = providers$CartoDB.DarkMatter) %>%
  addGlifyPolygons(data = ch_lu, 
                   color = cols, 
                   popup = "type",
                   group = "pols") %>%
  addMouseCoordinates() %>%
  setView(lng = 8.3, lat = 46.85, zoom = 9) %>% 
  addLayersControl(overlayGroups = "pols")
```

This works : 

``` r
ui <- fluidPage(
  leafletOutput("mymap"),
  tags$script(leaflet.glify:::glifyDependencies())
)

server <- function(input, output, session) {
  output$mymap <- renderLeaflet(m)
}

shinyApp(ui, server)
```

This doesn't :

``` r
ui <- fluidPage(
  tags$script(leaflet.glify:::glifyDependencies()),
  leafletOutput("mymap")
  
)

server <- function(input, output, session) {
  output$mymap <- renderLeaflet(m)
}

shinyApp(ui, server)
```

The reason why this does that is bcs the JS needs to be launched after the init of the leaflet. 

I wonder if : 

1. You could add this warning in the documentation? 

2. You could export `glifyDependencies` instead of having to to `:::` it

3. Maybe create a `glifyOutput()` function ?

``` r 
glifyOutput <- function(...){
  tagList(
    leafletOutput(...), 
    tags$script(leaflet.glify:::glifyDependencies())
  )
}

ui <- fluidPage(
  glifyOutput("mymap")
)

server <- function(input, output, session) {
  output$mymap <- renderLeaflet(m)
}

shinyApp(ui, server)
```

The third solution seems to be the most idiomatic and easier on the user  — no dependencies to manually add, and you don't have to specify it X time if you have X maps. 

Let me know if it sounds like a good idea, I'll be happy to make a PR. 

Colin

**Comment by tim-salabim** [comment]
Sounds like a very good idea thanks! 
A PR would be much appreciated as my shiny skills are limited.

**Comment by tim-salabim** [comment]
@ColinFay is there update on this? I see you have implemented something in your render branch? I am asking because I will very likely rename the package and want to avoid issues with open PRs

**Comment by ColinFay** [comment]
Hey @tim-salabim 

Yes sorry I meant to PR but that slipped my mind. 

Let me re-check everything and I'll send a PR in a few.

**Comment by tim-salabim** [comment]
Awesome! Again, thanks for this! Very much appreciated.

Note, I am planning to rename the package to `leafgl` , see [this comment](https://github.com/r-spatial/mapedit/issues/86#issuecomment-451657040) by @timelyportfolio in a recent mapedit issue discussion regarding naming schemes for R wrappers around leaflet addins (bullet 3). I agree with @timelyportfolio on this and will therefore rename this package too. 

In case you have any obstructions, let us know please.

**Comment by tim-salabim** [comment]
Also, I will likely need to wait until the weekend to merge everything, just so you know

**Comment by ColinFay** [comment]
Perfect ! 

Let me know if you need me to tweak something.

**Comment by tim-salabim** [comment]
@ColinFay I've merged your PRs. Again, thanks for those! I've also updated the readme to reflect the new shiny functionality. Furthermore, I've added you as an author to the package DESCRIPTION. If that is not ok with you please let me know and I'll remove you again. In any case, thanks for your contributions and have fun @ rstudioconf!

**Comment by ColinFay** [comment]
Hey, 

Thanks for merging. 
No problem for including me as `auth`, on the contrary!
